name: Call a reusable workflow
on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: GitRunnerOrg/workflow-called/.github/workflows/called.yaml@main
    with:
      some-value: main
